version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "python -c 'from backend.models import Base; from backend.database import engine; Base.metadata.create_all(bind=engine)' && uvicorn backend.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgis/postgis:13-3.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=psst_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d psst_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
